spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: hospital-service
  profiles:
    active:
    - dev
  config:
    import: "configserver:http://springconfigservice:8071"
